name 'cloud_ultra'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures cloud_ultra'
long_description 'Installs/Configures cloud_ultra'
version '0.1.0'
